export const INIT = 'INIT';
export const GET_MACHINES_ERROR = 'GET_MACHINES_ERROR';
export const GET_MACHINES_REQUEST = 'GET_MACHINES_REQUEST';
export const GET_MACHINES_SUCCESS = 'GET_MACHINES_SUCCESS';
export const GET_MACHINE_HEALTH_ERROR = 'GET_MACHINE_HEALTH_ERROR';
export const GET_MACHINE_HEALTH_REQUEST = 'GET_MACHINE_HEALTH_REQUEST';
export const GET_MACHINE_HEALTH_SUCCESS = 'GET_MACHINE_HEALTH_SUCCESS';